"""Frontend-neutral execution and Coding Harness contracts for Nexgent."""

from .coding_task import CodingTaskLoop, CodingTaskSummary, run_coding_task

from .contracts import (
    AcceptanceCriterion,
    ArtifactRecord,
    BudgetPolicy,
    DependencyEdge,
    Diagnosis,
    DiagnosisCandidate,
    EventKind,
    ExecutionEvent,
    ExperimentRun,
    FaultCategory,
    FaultObservation,
    FaultSpec,
    GoalSpec,
    RecoveryAction,
    RecoveryKind,
    RecoveryStrategy,
    RunMode,
    RunStatus,
    VerificationCheck,
    VerificationDecision,
    VerificationResult,
    VerificationStatus,
    WorkflowNode,
    WorkflowNodeResult,
    WorkflowNodeStatus,
    WorkflowPrimitive,
)
from .events import RuntimeEvent, RuntimeEventKind, emit_event
from .graph import (
    GraphExecutionError,
    GraphRunResult,
    GraphValidationError,
    PersistentTypedDAGRunner,
    TypedDAGRunner,
    WorkflowGraph,
    artifact_equivalent,
)
from .interactions import (
    InteractionBroker,
    InteractionKind,
    InteractionRequest,
    InteractionResponse,
)
from .service import NexgentRuntime
from .store import SQLiteRunStore
from .strategy import build_strategy_signature
from .telemetry import (
    ExternalSideEffect,
    HarnessTelemetry,
    MappingSimulatorAdapter,
    ResourceState,
    SimulatorAdapter,
    UnsafeSideEffectError,
)

__all__ = [
    "AcceptanceCriterion",
    "ArtifactRecord",
    "BudgetPolicy",
    "CodingTaskLoop",
    "CodingTaskSummary",
    "DependencyEdge",
    "Diagnosis",
    "DiagnosisCandidate",
    "EventKind",
    "ExecutionEvent",
    "ExperimentRun",
    "FaultCategory",
    "FaultObservation",
    "FaultSpec",
    "GoalSpec",
    "GraphExecutionError",
    "GraphRunResult",
    "GraphValidationError",
    "PersistentTypedDAGRunner",
    "InteractionBroker",
    "InteractionKind",
    "InteractionRequest",
    "InteractionResponse",
    "NexgentRuntime",
    "RecoveryAction",
    "RecoveryKind",
    "RecoveryStrategy",
    "RunMode",
    "RunStatus",
    "RuntimeEvent",
    "RuntimeEventKind",
    "SQLiteRunStore",
    "TypedDAGRunner",
    "VerificationCheck",
    "VerificationDecision",
    "VerificationResult",
    "VerificationStatus",
    "WorkflowNode",
    "WorkflowNodeResult",
    "WorkflowNodeStatus",
    "WorkflowGraph",
    "WorkflowPrimitive",
    "emit_event",
    "artifact_equivalent",
    "run_coding_task",
    "build_strategy_signature",
    "ExternalSideEffect",
    "HarnessTelemetry",
    "MappingSimulatorAdapter",
    "ResourceState",
    "SimulatorAdapter",
    "UnsafeSideEffectError",
]
